default[:openssh][:server][:permit_root_login] = 'yes'
default[:openssh][:server][:password_authentication] = 'no'
default[:openssh][:server][:port] = '22'
default[:openssh][:server][:use_p_a_m] = 'yes'
default[:openssh][:server][:print_motd] = 'no'
