name             'jenkins-slave'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures jenkins-slave-arm'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
# depends 'group'
depends 'openssh'
depends 'ruby_build'
depends 'user'
depends 'docker'
depends 'kernel_module'
