#
# Cookbook:: neon-image-syncd
# Recipe:: client
#
# Copyright:: 2017,  Harald Sitter
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

username = 'neon-image-sync'
groupname = username.clone
userhome = "/home/#{username}/"
gopath = '/home/neon-image-syncd'

systemd_dir = '/etc/systemd/system'
# We are not using socket activation for now.
systemd_units = %w[neon-image-sync.service neon-image-sync.timer]

importpath = 'github.com/apachelogger/neon-image-syncd'
srcdir = "#{gopath}/src/#{importpath}"

ohai 'reload_passwd' do
  action :nothing
  plugin 'etc'
end

group groupname do
  action :create
end

user username do
  home userhome
  group groupname
  manage_home true
  action :create
  notifies :reload, 'ohai[reload_passwd]', :immediately
end

directory "#{userhome}/.ssh" do
  owner username
  group groupname
  mode 0o700
end

# There is no reason to be more dynamic here, so we don't use the ssh cookbook
# but simply write the file as intended.
file "#{userhome}/.ssh/authorized_keys" do
  content <<-EOF
# Generated by Chef via neon-image-syncd cookbook; additions need to happen there
# Jenkins on drax:
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiLBt3u8Ldo3/bwIYI3t4QZ8yW7lMdWLy92gOxk0er5Rb1baKvubFIfTRL18I4FCvYJyzchCGZhxFfCkO5FiKNhOlKWbPJRKgitj1y6t02Jlyw0Z+zQXKe1srpwwQa2iN1LuTINcRoun/+Ouq52uQeRaye9zV3ikT+53/GcsfJTgxkJN2IOpIaLdEA3epuqnStpXdGYvAjycUngbVJASHWXsZUCPtZK6acxoxHvFPdroEVs+rB3HdWFUoaFECRJ8LQo21p7qlFIeC03scUmYs2cDaBne8h0NhA9q/0o+HQqaf2zam8fJiMqKo3eTYUt6jRStzxT+tpg3zyDlKsipL/ jenkins@do-neon-jenkins
  EOF
  owner username
  group groupname
  mode 0o600
  action :create
end

execute 'daemon-reload' do
  command 'systemctl daemon-reload'
  action :nothing
end

systemd_units.each do |unit_name|
  file "#{systemd_dir}/#{unit_name}" do
    content lazy { File.read("#{srcdir}/systemd/#{unit_name}") }
    notifies :run, 'execute[daemon-reload]', :immediately
  end

  systemd_unit unit_name do
    action [:enable, :restart]
  end
end

link "#{userhome}/sync" do
  to '/home/neon-image-syncd/sync'
  owner username
  group groupname
end
