#!/usr/bin/python

# Copyright Jonathan Riddell 2016
# May be copied under the GNU GPL 2 or later
#
# A script to remove old images built for Neon
# for each image type it saves images from today and yesterday and at least the
# most recent 5 and removes the rest
# This gets provisioned by images-nci cookbook to be run by cron as root on drax, the Neon jenkins/images server

from datetime import date
import os
from glob import glob
import shutil

def debug(string):
    print "prune-images: " + str(string)

class Pruner:
    baseDirectory = ""
    today = date.today().strftime('%Y%M%d')
    yesterday = date.fromordinal(date.today().toordinal()-1).strftime('%Y%M%d')

    def __init__(self, baseDirectory):
        debug("script prune-images")
        self.baseDirectory = baseDirectory
        os.chdir(self.baseDirectory)

    def getImageDirectories(self):
        self.topContents = os.listdir(".")

        debug(self.topContents)

        self.imageDirectories = []
        for directory in self.topContents:
            if os.path.exists(directory + "/current"):
                self.imageDirectories.append(directory)

        debug("image directories: " + str(self.imageDirectories))

    def removeDirectories(self):
        for directory in self.imageDirectories:
            os.chdir(directory)
            imageDirs = glob("20*") # fix in year 2099
            imageDirs.sort()
            debug("imageDirs" + str(imageDirs))
            self.removeImageDirs = imageDirs[:-5] # don't remove the most recent 5 images
            for dirname in self.removeImageDirs:
                if dirname.startswith(self.today) or dirname.startswith(self.yesterday):
                    self.removeImageDirs.remove(dirname)
            debug("removeImageDirs" + str(self.removeImageDirs))
            for directory in self.removeImageDirs:
                debug("removing " + directory)
                shutil.rmtree(directory)
            os.chdir("..")

if __name__ == '__main__':
    prune = Pruner("/var/www/images")
    prune.getImageDirectories()
    prune.removeDirectories()
